### ISSUE TITLE
Output simulated data in format that is ready to run

### ISSUE THREAD

**Issue by xylebori** [hahnlab/CAFExp#5]
Now it has columns for internal nodes, we should format so it is ready to run.

**Comment by benfulton** [comment]
Went back to a more CAFE4-like format, with tab-separation and a header line. Rather than identify the internal nodes by their related leaves, we assign them an arbitrary ID to keep the header lines from becoming untenable. Also, now producing two files; one "truth" file with internal nodes, and one including only the leaf nodes.
